default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: root
  password: root


development:
  <<: *default
  database: hey_url_development

test:
  <<: *default
  database: hey_url_test

production:
  <<: *default
  database: hey_url_production
